import {redirect} from 'next/navigation';
import Link from 'next/link';
import {getSessionUser} from '@/lib/auth';
import {prisma} from '@/lib/prisma';

const money=(k:number)=>`₦${(k/100).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default async function CompanyProjects(){
  const u=await getSessionUser();
  if(!u||!['COMPANY_ADMIN','COMPANY_STAFF'].includes(u.role))redirect('/login');
  const [projects,partners]=await Promise.all([
    prisma.project.findMany({include:{organization:true,milestones:{include:{partnerWork:{include:{partner:{include:{user:true}}}}},orderBy:{sequence:'asc'}}},orderBy:{updatedAt:'desc'}}),
    prisma.partnerProfile.findMany({where:{status:'APPROVED'},include:{user:true,capabilities:true},orderBy:{user:{name:'asc'}}})
  ]);
  return <main className="dashboard"><div className="pill">Company Control</div><h1>Projects & milestones</h1><p className="muted">Assign one milestone at a time, receive proof, then approve or reject the delivery.</p><div className="dashnav"><Link href="/company">Overview</Link><Link href="/company/clients">Clients</Link><Link href="/company/partners">Partners</Link><Link href="/company/services">Services</Link><Link href="/company/billing">Billing</Link><Link href="/company/projects">Projects</Link><Link href="/company/operations">Operations</Link></div><div className="stack">{projects.length===0?<div className="card"><p className="muted">No installment projects yet. Create a 2 or 3 installment invoice to create a project.</p></div>:projects.map(p=><div className="card" key={p.id}><div className="row"><div><h2>{p.title}</h2><p className="muted">{p.organization.name} · {p.installmentCount} installments · {money(p.totalAmountKobo)}</p></div><span className="badge">{p.status}</span></div><div className="stack">{p.milestones.map(m=><div className="card" key={m.id}><div className="row"><div><strong>{m.sequence}. {m.title}</strong><p className="muted">{m.description||'No milestone description.'}</p><p className="muted">Amount: {money(m.amountKobo)} · Status: {m.status}</p>{m.partnerWork?.partner?.user?<p className="muted">Partner: {m.partnerWork.partner.user.name}</p>:<p className="muted">Partner: Not assigned</p>}</div></div>{m.status==='SUBMITTED'&&<div className="card"><strong>Proof submitted</strong>{m.proofNote&&<p>{m.proofNote}</p>}{m.proofUrl&&<p><a href={m.proofUrl} target="_blank" rel="noreferrer">Open proof</a></p>}<div className="row"><form action="/api/company/projects" method="post"><input type="hidden" name="action" value="review"/><input type="hidden" name="milestoneId" value={m.id}/><input type="hidden" name="decision" value="approve"/><button className="btn" type="submit">Approve proof</button></form><form action="/api/company/projects" method="post"><input type="hidden" name="action" value="review"/><input type="hidden" name="milestoneId" value={m.id}/><input type="hidden" name="decision" value="reject"/><button className="btn" type="submit">Reject</button></form></div></div>}{!m.partnerWork&&m.status!=='LOCKED'&&<form className="stack" action="/api/company/projects" method="post"><input type="hidden" name="action" value="assign"/><input type="hidden" name="milestoneId" value={m.id}/><label>Assign approved partner<select name="partnerId" required><option value="">Select partner</option>{partners.map(x=><option key={x.id} value={x.id}>{x.user.name} — {x.capabilities.map(c=>c.name).join(', ')||'General'}</option>)}</select></label><button className="btn" type="submit">Assign milestone</button></form>}</div>)}</div></div>)}</div></main>;
}
