import {redirect} from 'next/navigation';
import Link from 'next/link';
import {getSessionUser} from '@/lib/auth';
import {prisma} from '@/lib/prisma';

const serviceNext={REQUESTED:['ACTIVE','CANCELLED'],ACTIVE:['PAUSED','COMPLETED'],PAUSED:['ACTIVE','COMPLETED'],COMPLETED:[],CANCELLED:[]};
const appNext={REQUESTED:['BUILDING','SUSPENDED'],BUILDING:['ACTIVE','DEGRADED','DOWN','SUSPENDED'],ACTIVE:['DEGRADED','DOWN','SUSPENDED','COMPLETED'],DEGRADED:['ACTIVE','DOWN','SUSPENDED'],DOWN:['ACTIVE','DEGRADED','SUSPENDED'],SUSPENDED:['BUILDING','ACTIVE','COMPLETED'],COMPLETED:[]};

export default async function CompanyOperations(){
  const u=await getSessionUser();
  if(!u||!['COMPANY_ADMIN','COMPANY_STAFF'].includes(u.role)) redirect('/login');
  const [services,apps,openTickets,pendingPartners]=await Promise.all([
    prisma.clientService.findMany({where:{status:{in:['REQUESTED','ACTIVE','PAUSED']}},include:{organization:true,service:true},orderBy:{updatedAt:'desc'}}),
    prisma.application.findMany({where:{status:{not:'COMPLETED'}},include:{organization:true},orderBy:{updatedAt:'desc'}}),
    prisma.supportTicket.findMany({where:{status:{in:['OPEN','IN_PROGRESS']}},include:{organization:true,user:true},orderBy:{createdAt:'desc'}}),
    prisma.partnerApplication.findMany({where:{status:'PENDING'},include:{user:true},orderBy:{createdAt:'asc'}})
  ]);
  return <main className="dashboard"><div className="pill">Company Control</div><h1>Operations</h1><p className="muted">One queue for work that needs Green Basket attention.</p><div className="dashnav"><Link href="/company">Overview</Link><Link href="/company/clients">Clients</Link><Link href="/company/partners">Partners</Link><Link href="/company/services">Services</Link><Link href="/company/billing">Billing</Link><Link href="/company/operations">Operations</Link><Link href="/company/support">Support</Link><Link href="/company/control">Control</Link></div><div className="stats"><div className="stat">Service work<strong>{services.length}</strong></div><div className="stat">Application work<strong>{apps.length}</strong></div><div className="stat">Open support<strong>{openTickets.length}</strong></div><div className="stat">Partner reviews<strong>{pendingPartners.length}</strong></div></div><div className="grid"><div className="card"><h2>Service lifecycle</h2>{services.length===0?<p className="muted">Nothing waiting.</p>:services.map(x=><div className="list-row" key={x.id}><div><strong>{x.service.name}</strong><span>{x.organization.name} · {x.status}</span></div><div className="row">{(serviceNext[x.status as keyof typeof serviceNext]||[]).map(s=><form key={s} action="/api/company/lifecycle" method="post"><input type="hidden" name="kind" value="service"/><input type="hidden" name="id" value={x.id}/><input type="hidden" name="status" value={s}/><button className="btn" type="submit">{s}</button></form>)}</div></div>)}</div><div className="card"><h2>Application lifecycle</h2>{apps.length===0?<p className="muted">No active application work.</p>:apps.map(x=><div className="list-row" key={x.id}><div><strong>{x.name}</strong><span>{x.organization.name} · {x.status}</span></div><div className="row">{(appNext[x.status as keyof typeof appNext]||[]).slice(0,3).map(s=><form key={s} action="/api/company/lifecycle" method="post"><input type="hidden" name="kind" value="application"/><input type="hidden" name="id" value={x.id}/><input type="hidden" name="status" value={s}/><button className="btn" type="submit">{s}</button></form>)}</div></div>)}</div><div className="card"><h2>Support queue</h2>{openTickets.length===0?<p className="muted">Queue is clear.</p>:openTickets.slice(0,8).map(x=><div className="list-row" key={x.id}><strong>{x.subject}</strong><span>{x.organization?.name||x.user.email}</span></div>)}</div><div className="card"><h2>Partner reviews</h2>{pendingPartners.length===0?<p className="muted">No pending applications.</p>:pendingPartners.map(x=><div className="list-row" key={x.id}><strong>{x.user.name}</strong><span>{x.capabilities}</span></div>)}</div></div></main>;
}